[book]
authors = ["Gijs Burghoorn"]
language = "en"
multilingual = false
src = "src"
title = "Power analysis Introductory Walkthrough"

[output.html]
git-repository-url = "https://github.com/coastalwhite/intro-power-analysis"
mathjax-support = true
